essensliebe/essensliebe/urls.py
from django.contrib import admin
from django.urls import path, include
from account.views import (login_view, register_view, logout_view,api_view) 
from profiles.views import profile, edit_profile, edit_food_prefrences, edit_partner_prefrences, prefrences, user_compose
from questions.views import questions_view, single
from directmessage.views import inbox, sent, compose, view_direct_message, reply
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from matches.views import matches_view
from likes.views import like_user
from dating.views import dating_view
from report.views import report_user


urlpatterns = [
	path('', include('home.urls')), 
    path('admin/', admin.site.urls),
    path('index/', include('home.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
	path('createdummydata/', api_view, name='api'), 
    path('register/', register_view, name='register'),
    path('questions/', questions_view, name='questions'),
    path('questions/<int:id>/', single, name='questions_single'),
    path('directmessage/inbox', inbox, name='inbox'),
    path('directmessage/sent', sent, name='sent'),
    path('directmessage/compose', compose, name='compose'),
    path('directmessage/view/<int:dm_id>/', view_direct_message, name='view_direct_message'),
    path('directmessage/view/<int:dm_id>/reply/', reply, name='reply'),
    path('profile/<str:username>/', profile, name='profile'),
    path('report/<int:user_id><str:username>/report_user', report_user, name='report_user'),
    path('profile/<str:username>/edit/', edit_profile, name='edit_profile'),
    path('profile/<int:user_id>/user_compose', user_compose, name='user_compose'),
    path('profile/<str:username>/prefrences', prefrences, name='prefrences'),
    path('profile/<str:username>/prefrences/partner', edit_partner_prefrences, name='edit_partner_prefrences'),
    path('profile/<str:username>/prefrences/food', edit_food_prefrences, name='edit_food_prefrences'),
    path('matches/', matches_view, name='matches_view'),
    path('like/<int:id>/', like_user, name='like_user'),
    path('dating/', dating_view, name='dating_view' )



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

essensliebe/home/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

essensliebe/report/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.signals import user_logged_in
from django.urls import reverse

# Create your models here.
user_obj = User.objects.get(username='admin')

QUEST = (
		('This person is annoying me', 'This person is annoying me'), 
		('They are pretending to be me or someone i know', 'They are pretending to be me or someone i know'),
		('They are sharing inappropriate or offensive message', 'They are sharing inappropriate or offensive message'),
		('This is a fake account', 'This is a fake account'),
        ('This profile represents a business or organization', 'This profile represents a business or organization'),
        ('They are using a different name than they use in everday life', 'They are using a different name than they use in everday life'),
		('other', 'other'),
        )


class UserReport(models.Model):
    report_category = models.CharField(max_length=100, choices=QUEST)
    reason_for_report = models.CharField(max_length=3000)
    report_url = models.CharField(max_length=3000)
    reporter = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_repot', null=True, blank=True)
    receiver = models.ForeignKey(User, on_delete=models.CASCADE,related_name='recived_report', null=True, blank=True)
    sent = models.DateTimeField(auto_now_add=False, auto_now=False, null=True, blank=True)
    read = models.BooleanField(default=False)
    read_at = models.DateTimeField(auto_now_add=False, auto_now=False, null=True, blank=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='parent_report', null=True, blank=True)
    replied = models.BooleanField(default=False)

    def __str__(self):
        return self.report_category

essensliebe/report/forms.py
from django import forms
from report.models import UserReport




class ReportForm(forms.ModelForm):

    class Meta:
        model = UserReport
        fields = ('report_category', 'reason_for_report')
        widgets= {
 
                'reason_for_report': forms.Textarea(attrs={'cols':80, 'row': 20}),
            }

essensliebe/report/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
import datetime
from .forms import ReportForm
from .models import UserReport
from django import forms
from report.models import UserReport

User = get_user_model()



def report_user(request, user_id, username):
    user = User.objects.get(id=user_id)
    #id=28 admin user
    admin = User.objects.get(id=28)
    form = ReportForm(request.POST or None)
    if form.is_valid():
        report_message = form.save(commit=False)
        report_message.reporter = user
        report_message.receiver = admin
        report_message.report_url = "http://127.0.0.1:8000/profile/" + username
        report_message.sent = datetime.datetime.now()
        report_message.save()
        return HttpResponseRedirect(reverse('index'))

    return render(request, 'report_user.html', locals())

essensliebe/report/templates/report_indox.html
{% extends "base.html" %}
{% block content %}
<div class="container">
        <div class="row">
                <div class="col-md-3">
                </div>
                <div class='col-lg-7'>
<table class="table table-striped">
    <thead>
    <th>From</th><th>Subject</th>
</thead>
    <tbody>
            {% for item in messages_in_reportinbox %}
        <tr>
            <td>
                {{ item.sender }}
            </td>
            <td>
                {% if item.read %}
                    <span style="color: rgb(32, 133, 192);" class='fa fa-check-square-o'></span>
                {% endif %}

             <a {% if item.read %} style="color: rgb(110, 105, 105);" {% endif %}href="{{ item.get_obsolute_url }}" > {{item.subject|truncatewords:10 }} </a>
             {% if item.sent %} <small>{{ item.sent }}</small> {% endif %} 
             </td>
        </tr>
        {% endfor%}
    </tbody>
</table>


{% endblock%}

essensliebe/report/templates/report_user.html
{% extends "base.html" %}
{% block title %} Compose {% endblock %}
{% block content %}

<div class="container">
    <div class="row">
            <div class="col-md-3">
                <br>
                <br>
                <a href="#" class="list-group-item">Home</a>
                <a href="/profile/edit" class="list-group-item">Edit Profile</a>
                <a href="/profile/prefrences" class="list-group-item">Edit Prefrences</a>
                {% if 'message' in request.get_full_path %}
                <a href="/directmessage/inbox" class="list-group-item">{% if not request.session.num_of_message == 0 %}<span class='badge pull-right'>{{ request.session.num_of_message }}</span>{% endif %}Inbox</a>
                <a href="/directmessage/compose" class="list-group-item">Compose</a>
                <a href="/directmessage/sent" class="list-group-item">Sent</a>
                {% endif %}
                <a href="#" class="list-group-item">Matchmaker</a>
            </div>
            <div class='col-lg-7'>
                <h3>Reporting Form</h3>
                <h4>Reporting User: {{ username }}</h4>
            <form action="report_user" method="POST">
                {% csrf_token %}
                {{ form.as_p }}         

                <p><label>Report url:</label>
                    <input type="text" name="report_url" size="40" value="http://127.0.0.1:8000/profile/{{ username }}" maxlength="120" required id="id_report_url"> </p>
                    <br>
                <input class='btn btn-defauly' type="submit">
                </form>

{% endblock%}